name: '🔖 Create Next Minor Release PR'
description: 'Automatically dispatches a next minor release'
branding:
  icon: 'git-pull-request'
  color: 'green'
inputs:
  GITHUB_TOKEN:
    description: 'Token for the repo'
    required: true
  MAIN:
    description: 'Main branch name - used for PR destination'
    required: false 
    default: 'main'
  DEVELOP:
    description: 'Develop branch name - used as ref to cut release branch from'
    required: false 
    default: 'develop'
  BOT_NAME:
    description: 'Name of the bot'
    required: false 
    default: 'knerd-bot'
  BOT_EMAIL:
    description: 'Email of the bot'
    required: false 
    default: 'contact@midnightnerd.com'
  PR_TEMPLATE:
    description: 'Template to use for PR creation'
    required: false 
    default: '.github/PULL_REQUEST_TEMPLATE.md'
  PR_DRAFT:
    description: 'Flag to turn on draft PRs'
    required: false 
  PR_LABEL: 
    description: 'label for PR'
    required: false 
  PR_ICON: 
    description: 'Emoji to use as prefix for PR'
    required: false 
    default: 🔖
  NPM_VERSION:
    description: 'Version to bump'
    required: false 
    default: minor

runs:
  using: 'composite'
  steps:
    - name: 🏗 Check out ${{ inputs.DEVELOP }} branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.DEVELOP }}
    - name: 🔧 Configure git
      shell: bash
      run: |
        git remote set-url origin https://x-access-token:${{ inputs.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git config --global user.email ${{ inputs.BOT_EMAIL }}
        git config --global user.name "${{ inputs.BOT_NAME }}" 
    - name: 🔖 Bump version
      shell: bash
      id: bump
      run: |
        npm version ${{ inputs.NPM_VERSION }} -m "${{ inputs.PR_ICON }} %s"
        VERSION=$(node -p "require('./package.json').version")
        echo "RELEASE=release-${{ inputs.NPM_VERSION }}/${VERSION}" >> $GITHUB_ENV

    - name: 🌿 Create branch
      shell: bash
      run: |
        RELEASE=${{ env.RELEASE }}
        git checkout -b $RELEASE
        git push -u origin $RELEASE
    - name: 🧐 Submit pull request
      id: pr
      uses: repo-sync/pull-request@1b6c62644f972d1a4cf98835ed1efe728d7497a8
      with:
        pr_label: ${{ inputs.PR_LABEL }} 
        pr_title: "${{ inputs.PR_ICON }} ${{ env.RELEASE }}"
        source_branch: ${{ env.RELEASE }}
        destination_branch: ${{ inputs.MAIN }}
        pr_template: ${{ inputs.PR_TEMPLATE }}   
        pr_draft: ${{ inputs.PR_DRAFT }} # Creates pull request as draft
        github_token: ${{ inputs.GITHUB_TOKEN }} 
